server:
  tomcat:
    connection-timeout: 18000000
spring:
  profiles:
    active: dev
  security:
    user:
      name: lijin
      password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd
    #这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
    time-zone: GMT+8
  mail:
    default-encoding: UTF-8
    username: 15549402651@163.com
    password: YBZMMDFBEENJWSDX
    host: smtp.163.com
    properties:
      mail:
        stmp:
          ssl:
            enable: true
            required: true
              # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
          # 默认25端口
    port: 25

mybatis-plus:
  mapper-locations:
    - classpath:mapper/**/*.xml
  typeAliasesPackage: com.hope.blog.*.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.hope.blog: debug
    org.springframework.data.elasticsearch.client.WIRE: TRACE
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ji8n3439n439n43ld9ne9343fdfer49h #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间ms
  tokenPrefix: 'Bearer '  #JWT负载中拿到开头
  expiration_remember: 60 * 60 * 24 * 7

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

secure:
  ignored:
    urls: #安全路径白名单,文件通配符一定要使用两个**
      - /needLogin
      - /swagger*//**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /sys/user/login
      - /sys/user/register
      - /blog/category/findAll
      - /blog/tag/findAll
      - /blog/tag/getTag
      - /blog/loop/findAll
      - /blog/nav/findAll
      - /blog/soul/random
      - /blog/photo/findAll
      - /blog/website/getNavigation
      - /comment/blogComment/commentsByArticleId
      - /comment/blogComment/save
      - /comment/blogCommentReplay/save
      - /blog/looper/findAll
      - /blog/article/list
      - /blog/article/search
      - /blog/article/{id}
      - /index.html